// Story scene graph for New Life Game.
//
// Scene shape:
//   {
//     bg:       { gradient, emoji }   // background style + a large emoji
//     text:     "what's on screen"
//     portrait: "images/bob.png" | undefined
//     label:    "optional caption shown top-left"
//     character: "bob"|"willie"|"peter"|"shared"|"extras"  // for Scene Selection grouping
//     title:    "human-readable title for Scene Selection"
//     choices:  [ { label, goto, subtle? } ]
//     hotspots: [ { x, y, w, h, goto, hint? } ]   // x/y/w/h in rem units
//     ending:   "win" | "game-over" | undefined
//   }
//
// Game logical space is ~1111x625 rem (16:9 body, scaled by updateScale()).

const BG = {
  outside: { gradient: "linear-gradient(#87ceeb, #ffe9bf)", emoji: "🏠" },
  inside: { gradient: "linear-gradient(#f5deb3, #d2b48c)", emoji: "🛋️" },
  outsideWork: { gradient: "linear-gradient(#5a6e7a, #8aa3b0)", emoji: "🏢" },
  insideWork: { gradient: "linear-gradient(#e8e3d6, #c8c2b3)", emoji: "💼" },
  loading: { gradient: "linear-gradient(#222, #444)", emoji: "⌛" },
  street: { gradient: "linear-gradient(#a9c8e0, #d0d8df)", emoji: "🛣️" },
  bus: { gradient: "linear-gradient(#0c1838, #2b4a8f)", emoji: "🚌" },
  debug: { gradient: "linear-gradient(#000, #001a00)", emoji: "🖥️" },
  gameOver: { gradient: "linear-gradient(#000, #2a0000)", emoji: "💀" },
  win: { gradient: "linear-gradient(#fff0a0, #ffd700)", emoji: "🏆" },
  fight: { gradient: "linear-gradient(#3a1010, #771010)", emoji: "🥊" },
  jam: { gradient: "linear-gradient(#7a0010, #c90016)", emoji: "🍓" },
  park: { gradient: "linear-gradient(#87ceeb, #6abe48)", emoji: "🌳" },
  garden: { gradient: "linear-gradient(#aed581, #689f38)", emoji: "🍅" },
  gym: { gradient: "linear-gradient(#cccccc, #888888)", emoji: "🏋️" },
  depot: { gradient: "linear-gradient(#444, #222)", emoji: "🏚️" },
  glow: { gradient: "linear-gradient(#dffd6e, #98e600)", emoji: "☢️" },
  trip: { gradient: "linear-gradient(#ff00ff, #00ffff)", emoji: "🌀" },
  cosmos: { gradient: "linear-gradient(#000033, #220044)", emoji: "🌌" },
  bar: { gradient: "linear-gradient(#3a1a0a, #1a0500)", emoji: "🍺" },
  doctor: { gradient: "linear-gradient(#e8f5e9, #b8d8ba)", emoji: "🩺" },
  crash: { gradient: "linear-gradient(#ff5500, #220000)", emoji: "💥" },
};

const BACK_TO_MENU = { label: "Back to menu", goto: "__menu__" };
const UHH_WHAT = { label: "Uhh what?", goto: "game-over-indecisive" };

// Reusable loading-screen factory: road-sign + walking character.
//   step 1 — character enters from off-screen-left, walks to the left of the sign
//   step 2 — character continues across, walking out off-screen-right
// Override `walk: { from, to }` (percentages of screen width) for custom motion.
function loadingStep(character, next, opts = {}) {
  const step = opts.step || 1;
  const defaultText = step === 2 ? "Still loading..." : "Loading...";
  const defaultWalk =
    step === 2 ? { from: 15, to: 110 } : { from: -15, to: 15 };
  const text = opts.text || defaultText;
  return {
    character,
    title: text,
    template: "road-sign",
    bg: BG.loading,
    text,
    walk: opts.walk || defaultWalk,
    choices: [{ label: "Continue", goto: next }],
  };
}

const SCENES = {
  // ───────────────────────── Shared endings ─────────────────────────
  "game-over-indecisive": {
    character: "shared",
    title: "Game Over — Indecisive",
    bg: BG.gameOver,
    text: "GAME OVER. \"Uhh what?\" Really? You picked a character, looked at them, and froze. They are embarrassed for you. So am I. Try committing to something. Anything.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-bus": {
    character: ["bob","willie"],
    title: "Game Over — Bus",
    bg: BG.bus,
    text: "GAME OVER. The bus wins. The bus always wins.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-radiation": {
    character: "peter",
    title: "Game Over — Radioactive",
    bg: BG.glow,
    text: "GAME OVER. You glow eternally. Your shadow continues to glow on the wall.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-bar": {
    character: "bob",
    title: "Game Over — Bar fight",
    bg: BG.bar,
    text: "GAME OVER. The bouncer wins. He always does. He is the size of a small horse.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-broke": {
    character: "bob",
    title: "Game Over — Broke",
    bg: BG.park,
    text: "GAME OVER. You are broke and the raccoon has your job now.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-crushed": {
    character: "bob",
    title: "Game Over — Crushed",
    bg: BG.gym,
    text: "GAME OVER. 700 kg was too much. The barbell waves at you sympathetically.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-tomato": {
    character: "willie",
    title: "Game Over — Tomato Man",
    bg: BG.garden,
    text: "GAME OVER. The Tomato Man always wins. He's been gardening longer than you've been alive.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-fitness": {
    character: "willie",
    title: "Game Over — Fitness",
    bg: BG.gym,
    text: "GAME OVER. You discover your lungs the hard way. You should've stuck to tomatoes.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-crash": {
    character: "peter",
    title: "Game Over — Crash",
    bg: BG.crash,
    text: "GAME OVER. The bus made contact with reality. Reality lost.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-deleted": {
    character: ["bob","peter"],
    title: "Game Over — Reality deleted",
    bg: BG.gameOver,
    text: "GAME OVER. There is no game. There is no over. There is nothing.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-clone": {
    character: "peter",
    title: "Game Over — Clone wins",
    bg: BG.debug,
    text: "GAME OVER. You always knew, deep down, he was the better Peter.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-shroom": {
    character: "bob",
    title: "Game Over — Bad trip",
    bg: BG.trip,
    text: "GAME OVER. The mushroom was not a friend. The mushroom never was.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },
  "game-over-bench": {
    character: "bob",
    title: "Game Over — Benched",
    bg: BG.park,
    text: "GAME OVER — BENCHED. Bob is now park furniture. He is finally useful to society.",
    ending: "game-over",
    choices: [BACK_TO_MENU],
  },

  // ── Convergence: the True Ending. Unlocked once Bob, Willie AND Peter have
  // each won. The Life Game itself reveals it's been watching the whole time.
  "convergence": {
    character: "shared",
    title: "Convergence",
    bg: BG.cosmos,
    text: "Bob the Smart. Willie the Rich. Peter the Stable. Three lives, lived. You stand together in a white room. The Life Game looks back at you. It speaks.",
    choices: [
      { label: "Listen", goto: "final-truth" },
      { label: "Walk away", goto: "final-walk" },
    ],
  },
  "final-truth": {
    character: "shared",
    title: "The Life Game speaks",
    bg: BG.cosmos,
    text: "\"You are the player. They are the lives. I am the Life Game. Three lives lived in full. Now the question — was it worth it?\"",
    choices: [{ label: "Yes", goto: "win-true" }],
  },
  "final-walk": {
    character: "shared",
    title: "Walk away",
    bg: BG.cosmos,
    text: "You walk out. The Life Game lets out a breath it's been holding for years.",
    choices: [{ label: "Become the game", goto: "win-cycle" }],
  },
  "win-true": {
    character: "shared",
    title: "True Ending",
    bg: BG.cosmos,
    text: "YOU WIN — THE TRUE ENDING. Same as the regular ending, but you get a sense of pride and accomplishment.",
    ending: "win",
    choices: [BACK_TO_MENU],
  },
  "win-cycle": {
    character: "shared",
    title: "You ARE the Life Game",
    bg: BG.cosmos,
    text: "YOU WIN — YOU ARE THE LIFE GAME. Time to run your own. The cycle continues.",
    ending: "win",
    choices: [BACK_TO_MENU],
  },
  win: {
    character: ["bob","willie","peter"],
    title: "You Win",
    bg: BG.win,
    text: "YOU WIN! A life well lived.",
    ending: "win",
    choices: [BACK_TO_MENU],
  },
  "win-enlightened": {
    character: ["bob","peter"],
    title: "Enlightened",
    bg: BG.cosmos,
    text: "YOU WIN — ENLIGHTENED. You are infinitely smart, fit, and probably haunted.",
    ending: "win",
    choices: [BACK_TO_MENU],
  },
  "win-tomato-king": {
    character: "willie",
    title: "Tomato King",
    bg: BG.garden,
    text: "YOU WIN — TOMATO KING. The harvest is eternal. Long live the King.",
    ending: "win",
    choices: [BACK_TO_MENU],
  },
  "win-glow": {
    character: "peter",
    title: "Pillar of Light",
    bg: BG.glow,
    text: "YOU WIN — RADIANT. You are a pillar of pure energy. Reality is now slightly green.",
    ending: "win",
    choices: [BACK_TO_MENU],
  },
  "win-fit-god": {
    character: "bob",
    title: "Fitness God",
    bg: BG.gym,
    text: "YOU WIN — FITNESS GOD. You teach calculus while bench-pressing buses.",
    ending: "win",
    choices: [BACK_TO_MENU],
  },
  "win-employed": {
    character: "willie",
    title: "Tomato CEO",
    bg: BG.garden,
    text: "YOU WIN — TOMATO CEO. You ripen quarterly. The shareholders are thrilled.",
    ending: "win",
    choices: [BACK_TO_MENU],
  },
  "win-cured": {
    character: "peter",
    title: "Cured",
    bg: BG.outside,
    text: "YOU WIN — CURED. You are a normal person now. Mostly. Sometimes you still hum.",
    ending: "win",
    choices: [BACK_TO_MENU],
  },
  "win-duplicate": {
    character: "peter",
    title: "Infinite Peter",
    bg: BG.debug,
    text: "YOU WIN — INFINITE PETER. The exponentially multiplying Peters quickly engulf the city, then the planet, and soon the entire universe, until there is no room for anything else.",
    ending: "win",
    choices: [BACK_TO_MENU],
  },

  // ───────────────────────────── BOB ─────────────────────────────
  "bob-start": {
    character: "bob",
    title: "Bob — Let's go!",
    bg: BG.outside,
    portrait: "images/bob.png",
    text: "You are Bob. You feel strong but a bit dim. Let's go!",
    choices: [
      { label: "OK", goto: "bob-load-1" },
      UHH_WHAT,
    ],
  },
  "bob-load-1": loadingStep("bob", "bob-load-2"),
  "bob-load-2": loadingStep("bob", "bob-outside-home", { step: 2 }),
  "bob-outside-home": {
    character: "bob",
    title: "Bob — Outside home",
    bg: BG.outside,
    portrait: "images/bob.png",
    text: "You stand outside your home. The mushrooms wave at you.",
    choices: [
      { label: "Go inside", goto: "bob-inside-home" },
      { label: "Go to the park", goto: "bob-park" },
      { label: "Go to the gym", goto: "bob-gym" },
    ],
    hotspots: [
      { x: 60, y: 360, w: 70, h: 70, goto: "bob-flower-shop", hint: "💐" },
    ],
  },

  // ── Bob's PARK branch (mushrooms → enlightenment) ──────────────
  "bob-park": {
    character: "bob",
    title: "Bob — Park",
    bg: BG.park,
    portrait: "images/bob.png",
    text: "The park. Birds. Pigeons. Two suspiciously similar mushrooms in the grass.",
    choices: [
      { label: "Sit on the bench", goto: "bob-park-bench" },
    ],
    hotspots: [
      { x: 720, y: 420, w: 50, h: 50, goto: "bob-shroom-eat", hint: "🍄" },
      { x: 220, y: 460, w: 50, h: 50, goto: "bob-bad-shroom", hint: "🍄" },
    ],
  },
  "bob-bad-shroom": {
    character: "bob",
    title: "Bob — Bad mushroom",
    bg: BG.trip,
    text: "You eat the OTHER mushroom. Wrong. Wrong wrong wrong. The colors are wrong.",
    choices: [{ label: "...", goto: "game-over-shroom" }],
  },
  "bob-park-bench": {
    character: "bob",
    title: "Bob — On the bench",
    bg: BG.park,
    portrait: "images/bob.png",
    text: "You sit. Nothing happens. You sit some more. A pigeon judges you.",
    choices: [
      { label: "Keep sitting", goto: "bob-park-bench-2" },
    ],
  },
  "bob-park-bench-2": {
    character: "bob",
    title: "Bob — Still on the bench",
    bg: BG.park,
    portrait: "images/bob.png",
    text: "Time passes. The pigeon has been joined by a parliament. They are voting on you.",
    choices: [
      { label: "Stand up", goto: "bob-park-bench-stand-2" },
      { label: "Keep sitting", goto: "bob-park-bench-3" },
    ],
  },
  "bob-park-bench-stand-2": {
    character: "bob",
    title: "Bob — Stand up?",
    bg: BG.park,
    portrait: "images/bob.png",
    text: "You stand! Briefly. The bench groans. Your knees groan louder. You sit back down.",
    choices: [{ label: "...", goto: "bob-park-bench-3" }],
  },
  "bob-park-bench-3": {
    character: "bob",
    title: "Bob — Bench-shaped",
    bg: BG.park,
    portrait: "images/bob.png",
    text: "You are now 40% bench. The bench is 60% you. The math is concerning.",
    choices: [
      { label: "Try to stand", goto: "bob-park-bench-stand-3" },
      { label: "Keep sitting", goto: "bob-park-bench-final" },
    ],
  },
  "bob-park-bench-stand-3": {
    character: "bob",
    title: "Bob — Can't stand",
    bg: BG.park,
    portrait: "images/bob.png",
    text: "You half-stand, half-doze. The raccoons converge. You barely notice.",
    choices: [{ label: "Drift off", goto: "bob-park-asleep" }],
  },
  "bob-park-bench-final": {
    character: "bob",
    title: "Bob — IS the bench",
    bg: BG.park,
    text: "You are the bench. The park has acquired a Bob-shaped bench. The pigeons sit on you.",
    choices: [{ label: "...", goto: "game-over-bench" }],
  },
  "bob-park-asleep": {
    character: "bob",
    title: "Bob — Asleep",
    bg: BG.park,
    text: "You fall asleep. A raccoon takes your wallet. It will need it more than you.",
    choices: [{ label: "...", goto: "game-over-broke" }],
  },
  "bob-shroom-eat": {
    character: "bob",
    title: "Bob — Eat the mushroom",
    bg: BG.park,
    portrait: "images/bob.png",
    text: "You eat the glowing mushroom. It tastes like ozone and licorice.",
    choices: [{ label: "Continue", goto: "bob-trip-1" }],
  },
  "bob-trip-1": {
    character: "bob",
    title: "Bob — Tripping",
    bg: BG.trip,
    text: "COLORS. So many colors. Your hands are made of bees.",
    choices: [{ label: "Continue", goto: "bob-trip-2" }],
  },
  "bob-trip-2": {
    character: "bob",
    title: "Bob — Deep trip",
    bg: BG.cosmos,
    text: "You float past Saturn. Saturn nods like it knows. You forget to ask anything.",
    choices: [{ label: "Continue", goto: "bob-enlightenment" }],
  },
  "bob-enlightenment": {
    character: "bob",
    title: "Bob — Enlightened",
    bg: BG.cosmos,
    portrait: "images/bob.png",
    text: "Bob is smart now. He thinks two thoughts in a row. He's never done that before.",
    choices: [{ label: "Embrace it", goto: "win-enlightened" }],
  },
  "bob-inside-home": {
    character: "bob",
    title: "Bob — Inside home",
    bg: BG.inside,
    portrait: "images/bob.png",
    text: "Inside. Your fridge has one egg and a sticky note: \"EAT ME LATER\". Bold of past Bob.",
    choices: [{ label: "Go to work", goto: "bob-load-3" }],
  },
  "bob-load-3": loadingStep("bob", "bob-load-4"),
  "bob-load-4": loadingStep("bob", "bob-outside-work", { step: 2 }),
  "bob-outside-work": {
    character: "bob",
    title: "Bob — Outside work",
    bg: BG.outsideWork,
    portrait: "images/bob.png",
    text: "The office. It hums quietly. Ominously.",
    choices: [{ label: "Go inside", goto: "bob-inside-work" }],
    hotspots: [
      { x: 920, y: 80, w: 130, h: 70, goto: "bob-ad-space", hint: "📋" },
    ],
  },
  "bob-inside-work": {
    character: "bob",
    title: "Bob — Inside work",
    bg: BG.insideWork,
    portrait: "images/bob.png",
    text: "You got paid +500! ...you also got fired. Boss says it's the haircut.",
    choices: [{ label: "Continue", goto: "bob-fired" }],
  },
  "bob-fired": {
    character: "bob",
    title: "Bob — Fired",
    bg: BG.insideWork,
    portrait: "images/bob.png",
    text: "You're alone in the office. What do you do?",
    choices: [
      { label: "Steal something", goto: "bob-steal" },
      { label: "Drown your sorrows", goto: "bob-bar" },
      { label: "Leave with dignity", goto: "bob-leave" },
    ],
  },
  "bob-steal": {
    character: "bob",
    title: "Bob — Steal",
    bg: BG.insideWork,
    portrait: "images/bob.png",
    text: "You rummage through the boss's drawer. Three things look interesting.",
    choices: [
      { label: "A book: \"Brain Manual\"", goto: "bob-find-book" },
      { label: "The boss's stapler", goto: "bob-take-stapler" },
      { label: "A USB stick labelled DO_NOT", goto: "bob-take-usb" },
    ],
  },
  "bob-find-book": {
    character: "bob",
    title: "Bob — Page 1",
    bg: BG.inside,
    portrait: "images/bob.png",
    text: "Home. You open the Brain Manual. Page 1: \"Think.\" You try. Something flickers, deep down.",
    choices: [{ label: "Page 2", goto: "bob-read-book" }],
  },
  "bob-read-book": {
    character: "bob",
    title: "Bob — Page 2",
    bg: BG.inside,
    portrait: "images/bob.png",
    text: "Page 2: \"Think harder.\" You think harder. Steam rises off your head. The mushrooms outside applaud.",
    choices: [{ label: "Skip ahead", goto: "bob-page-327" }],
  },
  "bob-page-327": {
    character: "bob",
    title: "Bob — Page 327",
    bg: BG.inside,
    portrait: "images/bob.png",
    text: "Page 327: a mirror. You stare. The mirror stares. You both know.",
    choices: [{ label: "Close the book", goto: "bob-get-smart" }],
  },
  "bob-get-smart": {
    character: "bob",
    title: "Bob — Smart now",
    bg: BG.inside,
    portrait: "images/bob.png",
    text: "You get smart. The boss was right about the haircut. The haircut was a metaphor. You finally see it.",
    choices: [{ label: "Live your best life", goto: "win" }],
  },
  "bob-take-stapler": {
    character: "bob",
    title: "Bob — Stapler",
    bg: BG.outside,
    portrait: "images/bob.png",
    text: "You pocket the boss's stapler. Ergonomic. Weighty. Yours now. You feel deeply armed.",
    choices: [{ label: "Go home", goto: "bob-stapler-home" }],
  },
  "bob-stapler-home": {
    character: "bob",
    title: "Bob — Stapler defense",
    bg: BG.inside,
    portrait: "images/bob.png",
    text: "Home. You arrange the stapler on the coffee table, just so. A bus drives through the living room wall. You staple it twice before going down.",
    choices: [{ label: "...", goto: "game-over-bus" }],
  },
  "bob-take-usb": {
    character: "bob",
    title: "Bob — USB stick",
    bg: BG.insideWork,
    portrait: "images/bob.png",
    text: "DO_NOT, the label says. You plug it into the boss's computer. The screen flashes green.",
    choices: [{ label: "Continue", goto: "bob-usb-debug" }],
  },
  "bob-usb-debug": {
    character: "bob",
    title: "Bob — Office debug menu",
    bg: BG.debug,
    portrait: "images/bob.png",
    text: "A debug menu fills the screen. Glowing buttons hum: SMART, RICH, DELETE_BOB. Somewhere far away, a bald man feels jealous.",
    choices: [
      { label: "Press SMART", goto: "win-enlightened" },
      { label: "Press RICH", goto: "win" },
      { label: "Press DELETE_BOB", goto: "game-over-deleted" },
    ],
  },
  "bob-leave": {
    character: "bob",
    title: "Bob — Leave",
    bg: BG.outsideWork,
    portrait: "images/bob.png",
    text: "You leave with your head held high. And empty.",
    choices: [{ label: "Go home", goto: "bob-back-to-town" }],
  },
  "bob-back-to-town": {
    character: "bob",
    title: "Bob — Back to town",
    bg: BG.street,
    portrait: "images/bob.png",
    text: "You walk home, thinking about lunch. Lunch doesn't think about you at all.",
    choices: [{ label: "Continue", goto: "bob-load-5" }],
    hotspots: [
      { x: 70, y: 280, w: 80, h: 120, goto: "bob-brick-wall", hint: "🧱" },
    ],
  },
  "bob-load-5": loadingStep("bob", "bob-load-6"),
  "bob-load-6": loadingStep("bob", "bob-hit-by-bus", { step: 2 }),
  "bob-hit-by-bus": {
    character: "bob",
    title: "Bob — Hit by bus",
    bg: BG.bus,
    text: "🚌💥 A bus driven by a strange bald man hits you head-on.",
    choices: [{ label: "...", goto: "game-over-bus" }],
  },

  // ───────────────────────────── WILLIE ─────────────────────────────
  "willie-start": {
    character: "willie",
    title: "Willie — Let's go!",
    bg: BG.outside,
    portrait: "images/willie.png",
    text: "You are Willie. Smart, broke, soft. Let's go!",
    choices: [
      { label: "OK", goto: "willie-load-1" },
      UHH_WHAT,
    ],
  },
  "willie-load-1": loadingStep("willie", "willie-load-2"),
  "willie-load-2": loadingStep("willie", "willie-outside-home", { step: 2 }),
  "willie-outside-home": {
    character: "willie",
    title: "Willie — Outside home",
    bg: BG.outside,
    portrait: "images/willie.png",
    text: "Home, sweet home. Something glints in the bushes. Tomato leaves rustle next door.",
    choices: [
      { label: "Go inside", goto: "willie-hit-by-bus" },
      { label: "Find a job", goto: "willie-job-hunt" },
      { label: "Walk it off", goto: "willie-park" },
    ],
    hotspots: [
      { x: 350, y: 470, w: 50, h: 70, goto: "willie-find-cheese", hint: "🍾" },
      { x: 60, y: 470, w: 80, h: 80, goto: "willie-tomato-garden", hint: "🍅" },
    ],
  },
  "willie-hit-by-bus": {
    character: "willie",
    title: "Willie — Hit by bus",
    bg: BG.bus,
    text: "🚌💥 The bus comes through the WALL? How? Why??",
    choices: [{ label: "...", goto: "game-over-bus" }],
  },
  "willie-find-cheese": {
    character: "willie",
    title: "Willie — Cheese bottle",
    bg: BG.outside,
    portrait: "images/willie.png",
    text: "A bottle of SWEDISH CLEAR LIQUID CHEESE. Distilled thrice. Label: one wink.",
    choices: [
      { label: "Drink it (??)", goto: "willie-drink-cheese" },
      { label: "Read the label", goto: "willie-cheese-label" },
    ],
  },
  "willie-cheese-label": {
    character: "willie",
    title: "Willie — Cheese label",
    bg: BG.outside,
    portrait: "images/willie.png",
    text: "Ingredients: cheese, water, regret. Made in Stockholm. Best before: 1987.",
    choices: [{ label: "Drink anyway", goto: "willie-drink-cheese" }],
  },

  // ── Willie's TOMATO branch (tomato king) ────────────────────────
  "willie-tomato-garden": {
    character: "willie",
    title: "Willie — Tomato garden",
    bg: BG.garden,
    portrait: "images/willie.png",
    text: "A magnificent tomato garden. Plump red orbs await your decisions.",
    choices: [
      { label: "Pick one tomato", goto: "willie-tomato-eat" },
      { label: "Take them ALL", goto: "willie-tomato-greedy" },
    ],
  },
  "willie-tomato-eat": {
    character: "willie",
    title: "Willie — Eat tomato",
    bg: BG.garden,
    portrait: "images/willie.png",
    text: "The tomato is perfect. Fitness +5. Wisdom +1. You feel ripe.",
    choices: [
      { label: "Eat another", goto: "willie-tomato-fit" },
      { label: "Save it for later", goto: "win-tomato-king" },
    ],
  },
  "willie-tomato-fit": {
    character: "willie",
    title: "Willie — Tomato powers",
    bg: BG.garden,
    portrait: "images/willie.png",
    text: "You are tomato now. The tomatoes accept you as their king.",
    choices: [{ label: "Accept your crown", goto: "win-tomato-king" }],
  },
  "willie-tomato-greedy": {
    character: "willie",
    title: "Willie — Greedy",
    bg: BG.garden,
    portrait: "images/willie.png",
    text: "47 tomatoes. The garden's owner manifests. He is large. He is angry. He is the Tomato Man.",
    choices: [
      { label: "Run", goto: "willie-tomato-chase" },
      { label: "Fight him", goto: "willie-tomato-loss" },
    ],
  },
  "willie-tomato-chase": {
    character: "willie",
    title: "Willie — Chased",
    bg: BG.garden,
    portrait: "images/willie.png",
    text: "You run. The Tomato Man is faster. The Tomato Man is always faster.",
    choices: [{ label: "Surrender", goto: "game-over-tomato" }],
  },
  "willie-tomato-loss": {
    character: "willie",
    title: "Willie — Tomato loss",
    bg: BG.garden,
    text: "You take a swing. The Tomato Man catches your fist in his fist. Squelch.",
    choices: [{ label: "...", goto: "game-over-tomato" }],
  },
  // ── Willie's PARK branch (no exercise pls) ─────────────────────
  "willie-park": {
    character: "willie",
    title: "Willie — Park",
    bg: BG.park,
    portrait: "images/willie.png",
    text: "The park. Pigeons. A jogger blurs past. A bench in the corner has a deeply familiar shape.",
    choices: [
      { label: "Sit on the bench", goto: "willie-bench" },
      { label: "Jog to the gym", goto: "willie-jog" },
      { label: "Go home", goto: "willie-outside-home" },
    ],
  },
  "willie-bench": {
    character: "willie",
    title: "Willie — Bench (Bob)",
    bg: BG.park,
    portrait: "images/willie.png",
    text: "You sit. The bench has Bob's face. The face smiles, faintly, from somewhere in the wood. You stand up at a polite speed.",
    choices: [{ label: "Pretend that didn't happen", goto: "willie-outside-home" }],
  },
  "willie-jog": {
    character: "willie",
    title: "Willie — Jogging",
    bg: BG.gym,
    portrait: "images/willie.png",
    text: "You jog three steps. Your lungs file a formal complaint. Your knees second the motion.",
    choices: [
      { label: "Push through", goto: "willie-collapse" },
      { label: "Walk home, defeated", goto: "willie-outside-home" },
    ],
  },
  "willie-collapse": {
    character: "willie",
    title: "Willie — Collapsed",
    bg: BG.gym,
    text: "You collapse on a treadmill. The treadmill keeps moving. You exit the gym at 12 km/h, backwards.",
    choices: [{ label: "...", goto: "game-over-fitness" }],
  },

  "willie-drink-cheese": {
    character: "willie",
    title: "Willie — Drink cheese",
    bg: BG.outside,
    portrait: "images/willie.png",
    text: "You gulp the cheese. The sky tilts. A donkey appears.",
    choices: [{ label: "Greet the donkey", goto: "willie-magic-donkey" }],
  },
  "willie-magic-donkey": {
    character: "willie",
    title: "Willie — Magic donkey",
    bg: BG.outside,
    portrait: "images/willie.png",
    text: "A MAGICAL MAGNETIZED DONKEY 🫏 makes you rich and ripped. Don't ask.",
    choices: [{ label: "Live forever", goto: "win" }],
  },

  // ───────────────────────────── PETER ─────────────────────────────
  "peter-start": {
    character: "peter",
    title: "Peter — Let's go!",
    bg: BG.outsideWork,
    portrait: "images/peter.png",
    text: "You are Peter. You drive a bus. You wanted to be a pilot. Pilots can't glow. Let's go!",
    choices: [
      { label: "OK", goto: "peter-load-1" },
      UHH_WHAT,
    ],
  },
  "peter-load-1": loadingStep("peter", "peter-load-2"),
  "peter-load-2": loadingStep("peter", "peter-home", { step: 2 }),
  "peter-home": {
    character: "peter",
    title: "Peter — Apartment",
    bg: BG.inside,
    portrait: "images/peter.png",
    text: "Your apartment hums. The fridge hums louder. A knock at the door — probably the neighbor, probably about the glow.",
    choices: [
      { label: "Answer the door", goto: "peter-neighbor" },
      { label: "Slip out the back", goto: "peter-depot" },
    ],
    hotspots: [
      { x: 820, y: 380, w: 60, h: 80, goto: "peter-555", hint: "📞" },
    ],
  },
  "peter-neighbor": {
    character: "peter",
    title: "Peter — Neighbor",
    bg: BG.inside,
    portrait: "images/peter.png",
    text: "\"Peter. Your fridge is glowing again.\" \"That's a feature.\" \"It's eating my fridge.\" You close the door, very gently.",
    choices: [{ label: "Head to work", goto: "peter-depot" }],
  },
  "peter-555": {
    character: "peter",
    title: "Peter — 555-LIFE",
    bg: BG.cosmos,
    portrait: "images/peter.png",
    text: "By the phone, a sticky note: \"555-LIFE.\" You dial. A voice answers, calm, ancient: \"...we've been waiting for you, Peter.\" Click. Dial tone.",
    choices: [{ label: "Back to the apartment", goto: "peter-home" }],
  },
  "peter-depot": {
    character: "peter",
    title: "Peter — Bus depot",
    bg: BG.depot,
    portrait: "images/peter.png",
    text: "The bus depot. Your bus glows softly. So do you. So does everything.",
    choices: [
      { label: "Start your shift", goto: "peter-bus" },
      { label: "Visit the doctor", goto: "peter-doctor" },
    ],
    hotspots: [
      { x: 920, y: 100, w: 40, h: 40, goto: "peter-lick-bus", hint: "✨" },
      { x: 100, y: 480, w: 40, h: 60, goto: "peter-meltdown-lever", hint: "🔴" },
    ],
  },
  "peter-lick-bus": {
    character: "peter",
    title: "Peter — Lick the bus",
    bg: BG.glow,
    portrait: "images/peter.png",
    text: "You lick the bus. Absorbing radiation feels GOOD. You start to glow.",
    choices: [{ label: "Glow harder", goto: "peter-pillar" }],
  },
  "peter-pillar": {
    character: "peter",
    title: "Peter — Pillar of light",
    bg: BG.glow,
    portrait: "images/peter.png",
    text: "You are a pillar of pure radioactive energy. The depot vibrates respectfully.",
    choices: [{ label: "Transcend", goto: "win-glow" }],
  },
  "peter-meltdown-lever": {
    character: "peter",
    title: "Peter — Meltdown",
    bg: BG.glow,
    text: "You pull the red lever. Klaxons. Heat. The depot melts. You melt. Everyone melts.",
    choices: [{ label: "...", goto: "game-over-radiation" }],
  },
  "peter-bus": {
    character: "peter",
    title: "Peter — Bus emergency",
    bg: BG.bus,
    portrait: "images/peter.png",
    text: "Your brakes don't work. You must choose. Now.",
    choices: [
      { label: "Into a building", goto: "peter-crash-building" },
      { label: "Into a pedestrian", goto: "peter-crash-bob" },
    ],
    hotspots: [
      { x: 970, y: 80, w: 24, h: 24, goto: "peter-debug-menu", hint: "🟢" },
    ],
  },
  "peter-crash-building": {
    character: "peter",
    title: "Peter — Building",
    bg: BG.crash,
    text: "💥 Crash. The building belonged to Willie. Sorry, Willie.",
    choices: [{ label: "...", goto: "game-over-crash" }],
  },
  "peter-crash-bob": {
    character: "peter",
    title: "Peter — Pedestrian",
    bg: BG.crash,
    text: "💥 Crash. The pedestrian was Bob. And then a lamp post. And then the abyss.",
    choices: [{ label: "...", goto: "game-over-crash" }],
  },
  "peter-debug-menu": {
    character: "peter",
    title: "Peter — Debug menu",
    bg: BG.debug,
    text: "You phase into a DEBUG MENU. Glowing buttons hum: MAX_STATS, DELETE_REALITY, ???",
    choices: [
      { label: "Press MAX_STATS", goto: "peter-max-stats" },
      { label: "Press DELETE_REALITY", goto: "peter-glitch" },
      { label: "Press ???", goto: "peter-clone-experiment" },
    ],
  },
  "peter-glitch": {
    character: "peter",
    title: "Peter — Reality deleted",
    bg: BG.gameOver,
    text: "You press DELETE_REALITY. Everything goes white. Then nothing. Then less than nothing.",
    choices: [{ label: "...", goto: "game-over-deleted" }],
  },
  "peter-max-stats": {
    character: "peter",
    title: "Peter — Max stats",
    bg: BG.debug,
    portrait: "images/peter.png",
    text: "You hover over MAX_STATS. A prompt appears: \"CONFIRM. Are you sure you earned this?\"",
    choices: [
      { label: "Yes.", goto: "peter-max-confirmed" },
      { label: "...no.", goto: "peter-max-honest" },
    ],
  },
  "peter-max-confirmed": {
    character: "peter",
    title: "Peter — Confirmed",
    bg: BG.debug,
    portrait: "images/peter.png",
    text: "You press confirm anyway. Stats: 💯 💯 💯. You did not earn this. But here we are.",
    choices: [{ label: "Reboot reality", goto: "win" }],
  },
  "peter-max-honest": {
    character: "peter",
    title: "Peter — Honest",
    bg: BG.debug,
    portrait: "images/peter.png",
    text: "You walk away. The button hums approvingly. Stats unchanged. You feel taller. Smarter. Earned.",
    choices: [{ label: "Ascend honestly", goto: "win-enlightened" }],
  },

  // ── Bob's GYM branch ────────────────────────────────────────────
  "bob-gym": {
    character: "bob",
    title: "Bob — Gym",
    bg: BG.gym,
    portrait: "images/bob.png",
    text: "The gym. Mirrors everywhere. A protein cloud hangs over the treadmills.",
    choices: [
      { label: "Push-ups", goto: "bob-gym-pushups" },
      { label: "Deadlift", goto: "bob-gym-deadlift" },
    ],
  },
  "bob-gym-pushups": {
    character: "bob",
    title: "Bob — Push-ups",
    bg: BG.gym,
    portrait: "images/bob.png",
    text: "1… 2… 200. You're at +50 fitness. The treadmill respects you now.",
    choices: [{ label: "Continue", goto: "bob-gym-deadlift" }],
  },
  "bob-gym-deadlift": {
    character: "bob",
    title: "Bob — Deadlift",
    bg: BG.gym,
    portrait: "images/bob.png",
    text: "The deadlift bar. 400 kg already on it. The plates whisper at you.",
    choices: [
      { label: "Lift it", goto: "bob-gym-buff" },
      { label: "Add more weight", goto: "bob-gym-failed" },
    ],
  },
  "bob-gym-failed": {
    character: "bob",
    title: "Bob — Lifting accident",
    bg: BG.gym,
    text: "You load 700 kg. You attempt the lift. You become one with the floor.",
    choices: [{ label: "...", goto: "game-over-crushed" }],
  },
  "bob-gym-buff": {
    character: "bob",
    title: "Bob — Buff",
    bg: BG.gym,
    portrait: "images/bob.png",
    text: "You lift like a god. In the locker room you find a small book: \"Lifting Philosophy\".",
    choices: [{ label: "Read it", goto: "bob-gym-smart" }],
  },
  "bob-gym-smart": {
    character: "bob",
    title: "Bob — Smart and buff",
    bg: BG.gym,
    portrait: "images/bob.png",
    text: "You speed-read Kant in four minutes. Intelligence: MAX. Triple threat unlocked.",
    choices: [{ label: "Ascend", goto: "win-fit-god" }],
  },

  // ── Bob's BAR branch ────────────────────────────────────────────
  "bob-bar": {
    character: "bob",
    title: "Bob — Bar",
    bg: BG.bar,
    portrait: "images/bob.png",
    text: "A dive bar. The bartender nods at you sympathetically. Or threateningly. Hard to tell.",
    choices: [
      { label: "Order a drink", goto: "bob-drinks" },
      { label: "Tip the bartender", goto: "bob-bartender" },
      { label: "Use the jukebox", goto: "bob-jukebox" },
      { label: "Talk to the bouncer", goto: "bob-talk-bouncer" },
    ],
  },
  "bob-bartender": {
    character: "bob",
    title: "Bob — Bartender",
    bg: BG.bar,
    portrait: "images/bob.png",
    text: "He pockets the tip and leans in. \"You're being watched, you know. The Life Game. Always have been. Three of you, even.\" He winks. You decide you need a drink.",
    choices: [{ label: "...", goto: "bob-drinks" }],
  },
  "bob-jukebox": {
    character: "bob",
    title: "Bob — Jukebox",
    bg: BG.bar,
    portrait: "images/bob.png",
    text: "Track A1: \"My Wife Left Me (And Took the Bus).\" Track A2: \"My Wife Left Me (Reprise).\" You play A1 three times. The whole bar joins in by the third.",
    choices: [{ label: "Back to the bar", goto: "bob-bar" }],
  },
  "bob-talk-bouncer": {
    character: "bob",
    title: "Bob — Bouncer",
    bg: BG.bar,
    portrait: "images/bob.png",
    text: "The bouncer is the size of a small horse. He nods. He has not spoken in eleven years. The silence is doing most of the talking.",
    choices: [
      { label: "Insult him anyway", goto: "game-over-bar" },
      { label: "Back away slowly", goto: "bob-bar" },
    ],
  },
  "bob-drinks": {
    character: "bob",
    title: "Bob — Drinks",
    bg: BG.bar,
    portrait: "images/bob.png",
    text: "Three drinks in. The room tilts. Money: -200. Wisdom: -10. Friends: +0.",
    choices: [
      { label: "One more", goto: "bob-bar-fight" },
      { label: "Stumble home", goto: "bob-drunk-home" },
    ],
  },
  "bob-bar-fight": {
    character: "bob",
    title: "Bob — Bar fight",
    bg: BG.bar,
    text: "You insult a stranger. He turns out to be the bouncer. He turns out to be very strong. He turns out to be the Tomato Man's cousin. Of course.",
    choices: [{ label: "...", goto: "game-over-bar" }],
  },
  "bob-drunk-home": {
    character: "bob",
    title: "Bob — Stumbling home",
    bg: BG.street,
    portrait: "images/bob.png",
    text: "You stagger toward home. A bus appears. The bus also notices you.",
    choices: [{ label: "...", goto: "bob-hit-by-bus" }],
  },

  // ── Willie's JOB branch ─────────────────────────────────────────
  "willie-job-hunt": {
    character: "willie",
    title: "Willie — Job hunt",
    bg: BG.street,
    portrait: "images/willie.png",
    text: "You walk into town. A neon sign reads: \"NOW HIRING — TOMATO EXPERTS\".",
    choices: [
      { label: "Enter", goto: "willie-interview-room" },
    ],
  },
  "willie-interview-room": {
    character: "willie",
    title: "Willie — Interview",
    bg: BG.insideWork,
    portrait: "images/willie.png",
    text: "An interview. The interviewer wears a tomato-print tie. He is very serious about it. A framed photo on his desk reads: \"Me & my brother (Tomato Man).\"",
    choices: [{ label: "Begin", goto: "willie-q1" }],
  },
  "willie-q1": {
    character: "willie",
    title: "Willie — Question 1",
    bg: BG.insideWork,
    portrait: "images/willie.png",
    text: "\"What is your greatest weakness?\"",
    choices: [
      { label: "Tomatoes", goto: "willie-q2" },
      { label: "Honesty", goto: "willie-interview-fail" },
      { label: "Lots of things", goto: "willie-q2" },
    ],
  },
  "willie-q2": {
    character: "willie",
    title: "Willie — Question 2",
    bg: BG.insideWork,
    portrait: "images/willie.png",
    text: "\"Why should we hire you?\"",
    choices: [
      { label: "I love tomatoes", goto: "willie-hired" },
      { label: "I have read about tomatoes", goto: "willie-hired" },
      { label: "I just need money", goto: "willie-interview-fail" },
    ],
  },
  "willie-hired": {
    character: "willie",
    title: "Willie — Hired",
    bg: BG.insideWork,
    portrait: "images/willie.png",
    text: "Hired! Money +9999. You are now Junior Tomato Expert.",
    choices: [{ label: "Continue", goto: "willie-promoted" }],
  },
  "willie-promoted": {
    character: "willie",
    title: "Willie — Promoted",
    bg: BG.insideWork,
    portrait: "images/willie.png",
    text: "Promoted in four minutes. Senior. Then VP. Then CEO. Then literally a tomato.",
    choices: [{ label: "Accept tomato-hood", goto: "win-employed" }],
  },
  "willie-interview-fail": {
    character: "willie",
    title: "Willie — Interview fail",
    bg: BG.insideWork,
    portrait: "images/willie.png",
    text: "The interviewer tosses you out the window. A bus is approaching.",
    choices: [{ label: "...", goto: "willie-hit-by-bus" }],
  },

  // ── Peter's DOCTOR branch ───────────────────────────────────────
  "peter-doctor": {
    character: "peter",
    title: "Peter — Doctor's office",
    bg: BG.doctor,
    portrait: "images/peter.png",
    text: "The doctor's office. Posters: \"PLEASE DO NOT GLOW IN THIS BUILDING.\"",
    choices: [
      { label: "Get a scan", goto: "peter-mri" },
    ],
  },
  "peter-mri": {
    character: "peter",
    title: "Peter — MRI",
    bg: BG.glow,
    portrait: "images/peter.png",
    text: "The MRI lights up like Times Square. A poster reads: \"Price guarantee — ALWAYS EXPENSIVE. © Elli's Medical Imaging.\" The doctor weeps with awe and mild concern.",
    choices: [{ label: "Continue", goto: "peter-treatment" }],
  },
  "peter-treatment": {
    character: "peter",
    title: "Peter — Treatment",
    bg: BG.doctor,
    portrait: "images/peter.png",
    text: "The doctor presents two options. \"Anti-radiation injection. Or — for our premium clients — the GLOW PACKAGE. Keep the gift. Embrace the gift.\" He slides a brochure across the desk. It is warm.",
    choices: [
      { label: "Take the injection", goto: "peter-cured-fridge" },
      { label: "Take the Glow Package", goto: "game-over-radiation" },
    ],
  },
  "peter-cured-fridge": {
    character: "peter",
    title: "Peter — Quiet",
    bg: BG.inside,
    portrait: "images/peter.png",
    text: "Cured. You go home. The fridge is dark — you forgot you were powering it yourself. The hum is gone. The silence is loud. You decide you like it.",
    choices: [{ label: "Live", goto: "win-cured" }],
  },

  // ── Peter's CLONE branch ────────────────────────────────────────
  "peter-clone-experiment": {
    character: "peter",
    title: "Peter — Cloning chamber",
    bg: BG.debug,
    portrait: "images/peter.png",
    text: "You press the button and a copy of you appears.",
    choices: [
      { label: "Duplicate", goto: "peter-duplicate" },
      { label: "Fight the clone", goto: "peter-fight-clone" },
    ],
  },
  "peter-duplicate": {
    character: "peter",
    title: "Peter — Duplicate",
    bg: BG.debug,
    portrait: "images/peter.png",
    text: "You press the button again, and so does your copy. The two new copies also press the button. The four new copies also press the button. The eight new copies also press the button. None of them are going to stop.",
    choices: [{ label: "Watch", goto: "win-duplicate" }],
  },
  "peter-fight-clone": {
    character: "peter",
    title: "Peter — Fight the clone",
    bg: BG.debug,
    text: "You swing at the clone. The clone swings back. He is a better Peter than you. You always knew.",
    choices: [{ label: "...", goto: "game-over-clone" }],
  },

  // ── Easter eggs from the OG: flower shop, ad space, brick wall ───
  "bob-flower-shop": {
    character: "bob",
    title: "Bob — Elli's Flower Shop",
    bg: { gradient: "linear-gradient(#ffe9bf, #f9d2c1)", emoji: "💐" },
    portrait: "images/bob.png",
    text: "ELLI'S FLOWER SHOP. The sign reads: \"Price guarantee — ALWAYS EXPENSIVE.\"",
    choices: [
      { label: "Buy a tulip (€200)", goto: "bob-flower-broke" },
      { label: "Just browse", goto: "bob-flower-thrown-out" },
      { label: "Leave", goto: "bob-inside-home" },
    ],
  },
  "bob-flower-broke": {
    character: "bob",
    title: "Bob — €200 tulip",
    bg: { gradient: "linear-gradient(#ffe9bf, #f9d2c1)", emoji: "🌷" },
    portrait: "images/bob.png",
    text: "€200 for one tulip. You accept because Elli is staring at you and you are weak.",
    choices: [{ label: "Continue", goto: "bob-inside-home" }],
  },
  "bob-flower-thrown-out": {
    character: "bob",
    title: "Bob — Thrown out",
    bg: { gradient: "linear-gradient(#ffe9bf, #f9d2c1)", emoji: "💐" },
    portrait: "images/bob.png",
    text: "Elli throws you out. \"Browsing is not free. Nothing is free.\" The door slams.",
    choices: [{ label: "Leave", goto: "bob-inside-home" }],
  },
  "bob-ad-space": {
    character: "bob",
    title: "Bob — Ad space for sale",
    bg: { gradient: "linear-gradient(#cccccc, #999999)", emoji: "📋" },
    portrait: "images/bob.png",
    text: "A weathered billboard: \"ADVERTISING SPACE FOR SALE. Call 555-LIFE.\" You memorize the number. Just in case.",
    choices: [{ label: "Look away", goto: "bob-inside-work" }],
  },
  "bob-brick-wall": {
    character: "bob",
    title: "Bob — Brick wall",
    bg: { gradient: "linear-gradient(#a0635a, #6e4a40)", emoji: "🧱" },
    portrait: "images/bob.png",
    text: "It's a brick wall. You stare. The brick wall does not stare back. This was a dead end.",
    choices: [{ label: "Walk away", goto: "bob-load-5" }],
  },

  // ───────────────────────────── EXTRAS: FIGHT ─────────────────────
  "fight-intro": {
    character: "extras",
    title: "Fight — Intro",
    bg: BG.fight,
    portrait: "images/loser.png",
    portraitRight: "images/jam-dude.png",
    text: "Welcome to LOSER vs JAM DUDE! 🥊 The crowd is mostly confused.",
    choices: [{ label: "Begin", goto: "fight-round-1" }],
  },
  "fight-round-1": {
    character: "extras",
    title: "Fight — Round 1",
    bg: BG.fight,
    portrait: "images/loser.png",
    portraitRight: "images/jam-dude.png",
    text: "Round 1! Loser flexes. Jam Dude oozes menacingly. Whom do you back?",
    choices: [
      { label: "Cheer for Loser", goto: "fight-round-2-loser" },
      { label: "Cheer for Jam Dude", goto: "fight-round-2-jam" },
      { label: "Just boo", goto: "fight-round-2-boo" },
    ],
  },
  "fight-round-2-loser": {
    character: "extras",
    title: "Fight — Round 2 (Loser)",
    bg: BG.fight,
    portrait: "images/loser.png",
    portraitRight: "images/jam-dude.png",
    text: "Loser hears you and starts crying with confidence. Jam Dude is unnerved.",
    choices: [{ label: "Round 3", goto: "fight-round-3-loser" }],
  },
  "fight-round-3-loser": {
    character: "extras",
    title: "Fight — Round 3 (Loser)",
    bg: BG.fight,
    portrait: "images/loser.png",
    portraitRight: "images/jam-dude.png",
    text: "Loser steps forward. Jam Dude steps in jam. He slips on himself. The crowd gasps. The referee, also confused, calls it a strike.",
    choices: [{ label: "Finish it", goto: "fight-loser-wins" }],
  },
  "fight-round-2-jam": {
    character: "extras",
    title: "Fight — Round 2 (Jam)",
    bg: BG.jam,
    portrait: "images/loser.png",
    portraitRight: "images/jam-dude.png",
    text: "Jam Dude grins. He extrudes a strawberry tendril toward the ring.",
    choices: [{ label: "Round 3", goto: "fight-round-3-jam" }],
  },
  "fight-round-3-jam": {
    character: "extras",
    title: "Fight — Round 3 (Jam)",
    bg: BG.jam,
    portrait: "images/loser.png",
    portraitRight: "images/jam-dude.png",
    text: "Loser punches Jam Dude. His fist sinks in to the wrist and stays there. They are now technically one entity. The referee adjusts his glasses.",
    choices: [{ label: "Finish it", goto: "fight-jam-wins" }],
  },
  "fight-round-2-boo": {
    character: "extras",
    title: "Fight — Round 2 (Boo)",
    bg: BG.fight,
    portrait: "images/loser.png",
    portraitRight: "images/jam-dude.png",
    text: "Both fighters look at you, hurt. They forget to fight.",
    choices: [{ label: "Ring the bell", goto: "fight-tie" }],
  },
  "fight-loser-wins": {
    character: "extras",
    title: "Fight — Loser wins",
    bg: BG.win,
    portrait: "images/loser.png",
    text: "LOSER WINS! By tears, by sheer audacity. The world is briefly fair.",
    choices: [{ label: "Back to extras", goto: "__extras__" }],
  },
  "fight-jam-wins": {
    character: "extras",
    title: "Fight — Jam Dude wins",
    bg: BG.jam,
    portraitRight: "images/jam-dude.png",
    text: "JAM DUDE WINS! 🍓 He is now the regional preserves champion.",
    choices: [{ label: "Back to extras", goto: "__extras__" }],
  },
  "fight-tie": {
    character: "extras",
    title: "Fight — Tie",
    bg: BG.fight,
    portrait: "images/loser.png",
    portraitRight: "images/jam-dude.png",
    text: "It's a tie. Everyone goes home. Nobody learns anything.",
    choices: [{ label: "Back to extras", goto: "__extras__" }],
  },
};

window.SCENES = SCENES;
